# Generated by Django 5.1.3 on 2024-11-14 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_catalog_mandatory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='frequency',
            field=models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly')], default='daily', max_length=20),
        ),
    ]
