# Generated by Django 5.1.3 on 2024-11-16 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_uploadedfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Delayed', 'Delayed'), ('Pending', 'Pending')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='frequency',
            field=models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly')], default='Daily', max_length=20),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='mandatory',
            field=models.CharField(choices=[('Is Mandatory', 'Is Mandatory'), ('Not Mandatory', 'Not Mandatory')], default='Is Mandatory', max_length=20),
        ),
    ]
