# Generated by Django 5.1.3 on 2024-11-19 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_productfield_field_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validationrule',
            name='custom_validation',
            field=models.CharField(blank=True, help_text='Custom validation rule', max_length=255, null=True),
        ),
    ]
