# Generated by Django 5.1.3 on 2024-11-19 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_validationrule_custom_validation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validationrule',
            name='date_format',
            field=models.CharField(blank=True, help_text="Expected date format, e.g., 'YYYY-MM-DD'", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='validationrule',
            name='picklist_values',
            field=models.TextField(blank=True, help_text='Comma-separated values if picklist is true', null=True),
        ),
    ]
