# Generated by Django 5.1.4 on 2024-12-11 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_uploadedfile_domain_uploadedfile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Delayed', 'Delayed'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
