# Generated by Django 4.2.17 on 2024-12-14 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_submissioninfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submissioninfo',
            name='record_ids',
        ),
    ]
