# Generated by Django 4.2.17 on 2024-12-16 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_remove_submissioninfo_record_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissioninfo',
            name='catalog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submission_info', to='catalog.catalog'),
        ),
        migrations.AddField(
            model_name='submissioninfo',
            name='domain',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
