# Generated by Django 4.2.17 on 2024-12-30 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homologation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomologationConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('corporate', models.CharField(max_length=255)),
                ('product', models.CharField(max_length=255)),
                ('responsible', models.CharField(max_length=255)),
                ('frequency', models.CharField(max_length=50)),
                ('db_ip', models.CharField(blank=True, max_length=255)),
                ('db_user', models.CharField(blank=True, max_length=255)),
                ('db_password', models.CharField(blank=True, max_length=255)),
                ('sftp_ip', models.CharField(blank=True, max_length=255)),
                ('sftp_user', models.CharField(blank=True, max_length=255)),
                ('sftp_password', models.CharField(blank=True, max_length=255)),
                ('non_homologated_products_mapping', models.BooleanField(default=False)),
                ('homologation_history_mapping', models.BooleanField(default=False)),
                ('stock_table_mapping', models.BooleanField(default=False)),
                ('email_configuration', models.BooleanField(default=False)),
                ('alert_configuration', models.BooleanField(default=False)),
                ('approved_emails', models.TextField(blank=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='homologationconfiguration',
            constraint=models.UniqueConstraint(fields=('id',), name='single_configuration'),
        ),
    ]
